// <auto-generated />
using System;
using Aminos.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aminos.Migrations
{
    [DbContext(typeof(AminosDB))]
    [Migration("20231203031637_V11_Add_Table_AnnAnnouncements")]
    partial class V11_Add_Table_AnnAnnouncements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Aminos.Core.Models.General.Tables.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("General.Activities");
                });

            modelBuilder.Entity("Aminos.Core.Models.General.Tables.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("General.Announcements");
                });

            modelBuilder.Entity("Aminos.Core.Models.General.Tables.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AccessTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Luid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExtId")
                        .IsUnique();

                    b.HasIndex("Luid")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("General.Cards");
                });

            modelBuilder.Entity("Aminos.Core.Models.General.Tables.Keychip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAccessDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("General.Keychips");
                });

            modelBuilder.Entity("Aminos.Core.Models.General.Tables.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLoginWebDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastPlayDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("General.UserAccounts");
                });

            modelBuilder.Entity("Aminos.Core.Models.General.Tables.Activity", b =>
                {
                    b.HasOne("Aminos.Core.Models.General.Tables.UserAccount", null)
                        .WithMany("Activities")
                        .HasForeignKey("UserAccountId");
                });

            modelBuilder.Entity("Aminos.Core.Models.General.Tables.Announcement", b =>
                {
                    b.HasOne("Aminos.Core.Models.General.Tables.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Aminos.Core.Models.General.Tables.Card", b =>
                {
                    b.HasOne("Aminos.Core.Models.General.Tables.UserAccount", null)
                        .WithMany("Cards")
                        .HasForeignKey("UserAccountId");
                });

            modelBuilder.Entity("Aminos.Core.Models.General.Tables.Keychip", b =>
                {
                    b.HasOne("Aminos.Core.Models.General.Tables.UserAccount", "Owner")
                        .WithMany("Keychips")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Aminos.Core.Models.General.Tables.UserAccount", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Cards");

                    b.Navigation("Keychips");
                });
#pragma warning restore 612, 618
        }
    }
}
