// <auto-generated />
using System;
using Aminos.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aminos.Migrations
{
    [DbContext(typeof(AminosDB))]
    [Migration("20231125104351_V9_Add_Tables_For_Keychip")]
    partial class V9_Add_Tables_For_Keychip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("Aminos.Models.General.Tables.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AccessTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Luid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExtId")
                        .IsUnique();

                    b.HasIndex("Luid")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("General.Cards");
                });

            modelBuilder.Entity("Aminos.Models.General.Tables.Keychip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAccessDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("General.Keychips");
                });

            modelBuilder.Entity("Aminos.Models.General.Tables.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLoginWebDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("General.UserAccounts");
                });

            modelBuilder.Entity("Aminos.Models.General.Tables.Card", b =>
                {
                    b.HasOne("Aminos.Models.General.Tables.UserAccount", null)
                        .WithMany("Cards")
                        .HasForeignKey("UserAccountId");
                });

            modelBuilder.Entity("Aminos.Models.General.Tables.Keychip", b =>
                {
                    b.HasOne("Aminos.Models.General.Tables.UserAccount", "Owner")
                        .WithMany("Keychips")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Aminos.Models.General.Tables.UserAccount", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Keychips");
                });
#pragma warning restore 612, 618
        }
    }
}
